# Site settings
title: Taocnrut
email: uskokovic
description: > # this means to ignore newlines until "baseurl:"
  Blogging something
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://taocnrut.github.io" # the base hostname & protocol for your site
twitter_username: taocnrut
github_username:  taocnrut

# Build settings
markdown: kramdown
